language: ruby
rvm:
- 2.3.3

# route your build to the container-based infrastructure for a faster build
sudo: false

script:
  - Make build
  - Make test

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
