language: ruby
rvm:
- 2.3.3

# route your build to the container-based infrastructure for a faster build
sudo: false

install:
  - bundle install
  - npm install
  - cp -r node_modules/font-awesome/fonts fonts/font-awesome

script:
  # Create _site
  - bundle exec jekyll build --config _config.yml,_config/production.yml

  # Run tests
  - bundle exec htmlproofer ./_site --check-opengraph --check-favicon --internal-domains $SITE_DOMAIN

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/node_modules

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    SITE_DOMAIN: keksi.io

# Deploy to gh-pages
deploy:
  skip_cleanup: true
  provider: script
  script: _scripts/travis-deploy-gh-pages.sh
  on:
    branch: master
