# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://keksi.io" # the base hostname & protocol for your site

# Pretty urls thank you
permalink: pretty

# Default values for missing data in posts
defaults:
  category: news
  author: hello@keksi.io
  author: onnimonni

navigation:
  about:
    title: 'About'
    post: about

# All authors
authors:
  onnimonni:
    email: onni@keksi.io
    name: Onni Hakala
    twitter: koodimonni
    facebook: monnionni
    github: onnimonni
    keybase: onnimonni
    uri: https://keybase.io/onnimonni
    gravatar: ffbe81bf9fa424901ddc06be226c98a4

sections:
  tutorials: 'Tutorials'

jekyll-archives:
  enabled: 'all'
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

settings:
# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Keksi.io
  name: Keksi Labs
  legal_name: Keksi Labs Oy

  avatar: logo.svg
  avatar_alt_text: Keksi Labs Logo
  gravatar: # Email MD5 hash
  description: "Full speed ahead in Web engineering" # used by search engines

  # Header and footer text
  header_text: >
     <h1> This is one-man engineering club focused in secure cloud services. </h1>
  header_text_feature_image:

  # Icons
  rss: true
  email_address: hello@keksi.io
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "KeksiLabs"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "keksiengineer"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-88238366-1
  disqus_shortname:
  muut_community_name: keksi # From muut.com settings, e.g. "muttcommunityname"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# Exclude non-site files
exclude: ['webpack.config.js', 'bin', 'vendor', 'LICENSE', 'CNAME', 'README.md', 'node_modules', 'licenses', 'package.json', 'Makefile', 'Gemfile', 'Gemfile.lock']

# SYNTAX HIGHLIGHTING
markdown: kramdown

# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false

# BUILD SETTINGS
sass:
  sass_dir: _sass
  style: :compressed

srcset:
  #cache: "/tmp/images"
  optipng: true
  # These are the maximum image sizes for 1x screen if someone tosses huge images into the content
  # this should be enough
  1x:
    width: 1280
    height: 720

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-srcset
  # Minify output
  - octopress-minify-html
  - jekyll/assets

# Always use digest in urls
assets:
  digest: true

ampdir: /amp
